"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";
import { createEvent, updateSiteSetting } from "@/lib/api";

const inputClass = "mt-2 w-full rounded border border-white/10 bg-black/35 px-4 py-3 outline-none focus:border-amber-300/50";

export default function AdminContentPage() {
  const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  async function saveEvent(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); setError(null); try { await createEvent({ slug:String(data.get("slug")), translations:{ en:{ title:String(data.get("title")), description:String(data.get("description")) } }, schedule:String(data.get("schedule")), timezone:String(data.get("timezone")), category:String(data.get("category")), reward_summary:String(data.get("reward")) || null, active:true }); event.currentTarget.reset(); setMessage("Event saved."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Save failed."); } }
  async function saveChannels(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); setError(null); try { await updateSiteSetting("contacts", Object.fromEntries(["email","phone","whatsapp","facebook","discord"].map((key) => [key, String(data.get(key) ?? "")] ))); await updateSiteSetting("stream", { platform:String(data.get("platform") ?? ""), url:String(data.get("streamUrl") ?? ""), active:Boolean(data.get("streamActive")) }); setMessage("Contacts and stream saved."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Save failed."); } }
  return <main className="min-h-screen bg-[#07080b] px-6 py-16 text-white"><div className="mx-auto max-w-5xl"><div className="flex items-end justify-between"><div><p className="mu-kicker">Admin dashboard</p><h1 className="mt-3 text-4xl font-black">Site content</h1></div><Link href="/" className="text-sm text-amber-300">View website →</Link></div><p className="mt-4 text-sm text-amber-200/60">Development dashboard — authentication is required before production.</p>{message && <p className="mt-6 text-emerald-400">{message}</p>}{error && <p className="mt-6 text-red-400">{error}</p>}<div className="mt-10 grid gap-8 lg:grid-cols-2"><form onSubmit={saveEvent} className="mu-panel rounded-xl p-8"><div className="relative space-y-4"><h2 className="text-2xl font-black">Add event</h2>{[["slug","Slug"],["title","English title"],["description","English description"],["schedule","Schedule / cron"],["timezone","Timezone"],["category","Category"],["reward","Reward summary"]].map(([name,label]) => <label key={name} className="block text-xs font-bold uppercase tracking-wider text-gray-400">{label}<input name={name} required={!['description','reward'].includes(name)} defaultValue={name === "timezone" ? "UTC" : undefined} className={inputClass}/></label>)}<button className="w-full rounded bg-amber-400 py-3 font-black text-black">SAVE EVENT</button></div></form><form onSubmit={saveChannels} className="mu-panel rounded-xl p-8"><div className="relative space-y-4"><h2 className="text-2xl font-black">Contacts & stream</h2>{[["email","Email"],["phone","Telephone"],["whatsapp","WhatsApp"],["facebook","Facebook URL"],["discord","Discord URL"],["platform","Stream platform"],["streamUrl","Stream URL"]].map(([name,label]) => <label key={name} className="block text-xs font-bold uppercase tracking-wider text-gray-400">{label}<input name={name} className={inputClass}/></label>)}<label className="flex items-center gap-3 text-sm"><input name="streamActive" type="checkbox"/> Stream active</label><button className="w-full rounded bg-amber-400 py-3 font-black text-black">SAVE CHANNELS</button></div></form></div></div></main>;
}
